buildVariable: false
familyName: Noto Sans Elymaic
googleFonts: true
includeSubsets:
- from:
    repo: notofonts/latin-greek-cyrillic
    path: sources/NotoSans-Italic.glyphspackage
  name: GF_Latin_Core
sources:
- NotoSansElymaic.designspace
